version: '3'

services:
  prometheus:
    container_name: prometheus
    image: "hub.docker.prod.walmart.com/prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-local.yml:/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: "hub.docker.prod.walmart.com/grafana/grafana"
    ports:
      - "3000:3000"