version: '3'

services:
  local-couchbase:
    container_name: couchbase-local
    image: couchbase/server
    volumes:
      - ~/couchbase:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210